"""use new models Page and User

Revision ID: bbd69a216a94
Revises: 82cd8d364d79
Create Date: 2019-12-05 16:30:44.516637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd69a216a94'
down_revision = '82cd8d364d79'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
