"""userLoginTable

Revision ID: ed03c28c2242
Revises: 4f5c10e91957
Create Date: 2019-12-16 12:23:45.281547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed03c28c2242'
down_revision = '4f5c10e91957'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserLogin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_UserLogin')),
    sa.UniqueConstraint('email', name=op.f('uq_UserLogin_email'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserLogin')
    # ### end Alembic commands ###
