"""init

Revision ID: 7fc8ea645cc1
Revises: 6e8cc22f0531
Create Date: 2019-12-13 18:14:36.361220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc8ea645cc1'
down_revision = '6e8cc22f0531'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('lastName', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'lastName')
    # ### end Alembic commands ###
