"""userprofile

Revision ID: dc541e523038
Revises: bb2d727522b3
Create Date: 2019-12-23 18:14:46.216620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc541e523038'
down_revision = 'bb2d727522b3'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserProfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('mobileNo', mysql.BIGINT(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('password', sa.String(length=25), nullable=False),
    sa.Column('user_Type', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_UserProfile')),
    sa.UniqueConstraint('email', name=op.f('uq_UserProfile_email'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserProfile')
    # ### end Alembic commands ###
