"""userprofile

Revision ID: bb2d727522b3
Revises: 62308da20f17
Create Date: 2019-12-23 18:12:45.451241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2d727522b3'
down_revision = '62308da20f17'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
